### ISSUE TITLE
Fork or not to fork

### ISSUE THREAD

**Issue by AJenbo** [Fusion/s2ajax#1]
Just noticed that we both have worked on a new version of Sajax, maybe we should look at merging some of the work in to an even newer version :)
http://github.com/AJenbo/Sajax

**Comment by Fusion** [comment]
I guess. We would have to compare notes, I guess.
1. I only modified the PHP version, I have been too lazy to touch Ruby or Python so that's kind of a limited update
2. My modifications represent a fairly extensive change of philosophy with regards to how PHP and JS communicate, you may not wish to go there
3. What do your modifications entail so far?

Cheers,
-Chris.
